# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: FluentLenium CI pipeline

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  java8-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Java 8 - unit & integration tests
      run: mvn -Pjava8 clean verify --file pom.xml
  java11-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Java 11 - unit & integration tests
      run: mvn -Pframework-integration-tests,java11 -pl '!fluentlenium-integration-tests,!fluentlenium-cucumber,!fluentlenium-spock,!fluentlenium-coverage-report,!fluentlenium-spring-testng' clean test --file pom.xml
    - name: Java 11 - unit & integration tests code coverage + snapshot upload
      run: |
        mvn -Pjava11 clean verify jacoco:report --file pom.xml
        mvn -Pjava11 coveralls:report --file pom.xml
        mvn -Pjava11 deploy -DskipTests --settings deploy-settings.xml --file pom.xml    
        
  java11-javadoc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Java 11 - JavaDoc
      run: mvn -Pjava11 javadoc:aggregate   
  java11-examples:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Java 11 - compile examples
      run: mvn -Pexamples,java11 clean compile   
    - name: Java 11 - compile Kotlin examples
      run: |
        chmod +x examples/quickstart-firefox/gradlew
        chmod +x examples/quickstart-firefox/gradle/wrapper/gradle-wrapper.jar
        cd examples/quickstart-firefox
        ./gradlew test build -x test      
